;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-five-chars
	backward-five-lines
	backward-sexp
	beginning-of-buffer
	beginning-of-defun
	delete-horizontal-space
	dired-mark
	end-of-defun
	eval-expression
	eval-print-last-sexp
	forward-five-chars
	forward-five-lines
	forward-sexp
	ibuffer-mark-for-delete
	kill-region
	kill-sentence
	mark-paragraph
	mjb/er/expand-region
	transpose-words
	yaml-electric-bar-and-angle
	yaml-electric-dash-and-dot
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	ein:worksheet-execute-cell-and-goto-next
	ibuffer-do-kill-on-deletion-marks
	ido-switch-buffer
	mjb-mc-map
	mjb/mc/cycle-backward
	mjb/mc/cycle-forward
	mjb/mc/insert-numbers
	mjb/mc/mark-all-in-region-regexp
	mjb/mc/mark-all-like-this
	mjb/mc/mark-next-like-this-word
	mjb/mc/mark-next-lines
	mjb/mc/mark-pop
	mjb/mc/mark-previous-like-this
	mjb/mc/mark-previous-lines
	mjb/mc/reverse-regions
	mjb/mc/skip-to-next-like-this
	mjb/mc/skip-to-previous-like-this
	mjb/mc/sort-regions
	mjb/mc/unmark-next-like-this
	mjb/mc/unmark-previous-like-this
	repeat
	set-rectangular-region-anchor
	smex
	wgrep-change-to-wgrep-mode
	wgrep-finish-edit
	xref-find-definitions
	))
